### ISSUE TITLE
not able to register and try any feature

### ISSUE THREAD

**Issue by CDSLabs** [shashank-sharma333/ModernPayroll#4]
no matter, which email I use, I get error email already registered.

**Comment by shashank-sharma333** [comment]
Dear Professor,
I hope you are doing well!. Apologies for the inconvenience. It seems our server was not responding. Please find the updated server URL below:-

http://54.212.140.4:3000/login

Also, we would be happy to hop on a call, if you require any assistance with running the application 
Kindly let us know if you require any other details

Regards,
Shashank Sharma
